urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.contrib import auth
import os

admin.autodiscover()


urlpatterns = patterns('',
	(r'^admin/', include(admin.site.urls)),
	(r'^static/(?P<path>.*)$','django.views.static.serve',
		{'document_root': os.path.join(settings.PROJECT_DIR, "static") }),
   	(r'^admin/static/(?P<path>.*)$','django.views.static.serve',
		{'document_root': os.path.join(settings.PROJECT_DIR, "static/admin") }),


	(r'^accounts/logout/?$', 'users.views.logout_view'),
	(r'^accounts/login/?$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
	(r'^accounts/?$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
	(r'^accounts/', include('registration.backends.default.urls')),

	# (r'^accounts/login/?$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
	# (r'^accounts/logout/?$', 'django.contrib.auth.views.logout', {'template_name': 'login.html'}),
	
	
	
	
	(r'^base/', 'projects.views.base'),
	(r'^ajax/users','projects.views.ajaxUsers'),
	(r'^ajax/metrics','risk_models.views.ajaxMetrics'),

	(r'^/?$','projects.views.projectIndex'),
	(r'^projects/?$','projects.views.projectIndex'),
	(r'^projects/(index)?/?$','projects.views.projectIndex'),
	(r'^projects/(new|add)/?$','projects.views.projectAdd'),
	
	(r'^projects/(?P<project_id>\d+)/?$','projects.views.projectSettings'),
	(r'^projects/(?P<project_id>\d+)/admin(istration)?/?$','projects.views.projectSettings'),
	
	(r'^projects/(?P<project_id>\d+)/communities/(?P<community_id>\d+)/?$', 'communities.views.survey'),
	(r'^projects/(?P<project_id>\d+)/communities/(?P<community_id>\d+)/observations/?$', 'communities.views.observations'),
	(r'^projects/(?P<project_id>\d+)/communities/(?P<community_id>\d+)/survey/?$', 'communities.views.survey'),
	(r'^projects/(?P<project_id>\d+)/communities/(?P<community_id>\d+)/administration/?$', 'communities.views.administration'),
	
	(r'^projects/(?P<project_id>\d+)/risk(-matrix)?/?$', 'projects.views.riskMatrix'),
	(r'^projects/(?P<project_id>\d+)/admin(istation)?/?$', 'projects.views.administration'),
	
	(r'^projects/(?P<project_id>\d+)/users/?$', 'projects.views.userList'),
	(r'^projects/(?P<project_id>\d+)/users/(add|new)(\-user)?/?$', 'projects.views.userAdd'),
	
	(r'^projects/(?P<project_id>\d+)/communities/?$', 'projects.views.communityList'),
	(r'^projects/(?P<project_id>\d+)/communities/(add|new)(-community)?/?$', 'projects.views.communityAdd'),
	
	(r'^projects/(?P<project_id>\d+)/metrics/?$', 'projects.views.metricList'),
	(r'^projects/(?P<project_id>\d+)/metrics/(?P<metric_id>\d+)/?$', 'risk_models.views.metric',{'is_new': False}),
	(r'^projects/(?P<project_id>\d+)/metrics/new(-metric)?/?$', 'risk_models.views.metric',{'is_new': True}),
	
	(r'^projects/(?P<project_id>\d+)/models/?$', 'projects.views.riskModelList'),
	(r'^projects/(?P<project_id>\d+)/models/(?P<riskModel_id>\d+)(/edit)?/?$', 'risk_models.views.riskModel',{'is_new': False}),
	(r'^projects/(?P<project_id>\d+)/models/(add|new)(-model)?/?$', 'risk_models.views.riskModelNew'),
	(r'^projects/(?P<project_id>\d+)/models/(?P<riskModel_id>\d+)/(add|new)(-metric)?/?$', 'risk_models.views.metricLinkNew'),
	
	
	(r'^projects/(?P<project_id>\d+)/observations/?$', 'projects.views.observationList'),
	(r'^projects/(?P<project_id>\d+)/observations/(?P<observation_id>)/?$', 'risk_models.views.observation'),
	(r'^projects/(?P<project_id>\d+)/observations/new(-observation)?/?$', 'risk_models.views.observation',{'is_new': True}),

	
	# (r'^models/?$', 'risk_models.views.riskModelList'),
	# (r'^models/(?P<riskModel_id>\d+)/?', 'risk_models.views.riskModel'),
	# (r'^models/new/?', 'risk_models.views.riskModel'),
	
	
	
)

risk_models/models.py
from django.db import models
# from django.contrib.gis.db import models
from django.contrib.auth.models import User

from django.forms.models import inlineformset_factory
from django.forms.models import modelformset_factory
from django.forms import ModelForm, Textarea, RadioSelect


TYPE_CHOICES = (
	('M', 'Multiple choice'),
	('D', 'Numeric')
)

MISSING_POLICIES = (
	('D', 'Default Value'),
	('A', 'Average/Mode Value'),
	('I', 'Invalidate'),
)

DUPLICATE_POLICIES = (
	('R', 'Use Most Recent'),
	('A', 'Use the average value'),
	('I', 'Invalidate'),
)

class Metric(models.Model):
	name = models.CharField(max_length=200,unique=True)

	project = models.ForeignKey('projects.project')
	
	minimumValue = models.DecimalField(max_digits=19,decimal_places=10,blank=True,null=True)
	maximumValue = models.DecimalField(max_digits=19,decimal_places=10,blank=True,null=True)
	precision = models.IntegerField(blank=True,null=True)
	unitOfMeasure = models.CharField(max_length=100,blank=True,null=True)
	
	metricType = models.CharField(max_length=1,choices=TYPE_CHOICES,blank=False,null=False,default='D')
	
	def type(self):
		return metricType
		
	def __unicode__(self):
		return self.name


class MCOption(models.Model):
	name = models.CharField(max_length=200)
	metric = models.ForeignKey('Metric')

	def __unicode__(self):
		return self.name
		

# ModelFormSet = inlineformset_factory(models.RiskModel, models.Metric,formset=BaseBuildingFormset, extra=1)

class MCScore(models.Model):
	# TODO: do we need the option fk?
	option = models.ForeignKey('MCOption')
	modelMetricLink = models.ForeignKey('ModelMetricLink')
	score = models.DecimalField(max_digits=19,decimal_places=10)
	
	def __unicode__(self):
		return "%s<->%s" % (self.option.name,self.modelMetricLink.riskModel.name)
		
	class Meta:
	 	unique_together = ("option", "modelMetricLink")

class Observation(models.Model):
	community = models.ForeignKey('communities.Community')
	metric = models.ForeignKey('risk_models.Metric')
	user = models.ForeignKey('users.MossaicUser',null=True,blank=True)
	timestamp = models.DateTimeField(auto_now=True)
	
	value = models.DecimalField(max_digits=19,decimal_places=10,blank=True,null=True)
	mcValue = models.ForeignKey('risk_models.MCOption',blank=True,null=True)
		
	def __unicode__(self):
		return (self.community.name + ": " + self.metric.name)

class ModelMetricLink(models.Model):
	riskModel = models.ForeignKey('RiskModel')
	metric = models.ForeignKey('Metric')
	transformation = models.CharField(max_length=200,blank=True,null=True)
	
	weight = models.DecimalField(max_digits=19,decimal_places=10,blank=True,null=True)
	
	defaultDecimalValue = models.DecimalField(max_digits=19,decimal_places=10,null=True,blank=True)
	defaultMCValue = models.ForeignKey('MCOption',null=True,blank=True)
	# ,choices=metric.mcoption_set)
	
	missingValuePolicy = models.CharField(max_length=1,choices=MISSING_POLICIES,default="I")
	
	duplicateValuePolicy = models.CharField(max_length=1,choices=MISSING_POLICIES,default="A")
	
	def eval(self,community):
		val = self.eval_raw(community)
		if self.metric.metricType == 'D' and self.transformation != '':
			try:
				x = val
				val = eval(self.transformation.replace('^','**')) 
			except:
				return None
			return self.weight * val
		else:
			return val
		
	def eval_raw(self,community):
		observations = Observation.objects.filter(community__id__exact=community.id,metric__id__exact=self.metric.id)
		nobs = observations.count()
		
		if nobs == 1:
			if self.metric.metricType == "M":
				return observations[0].mcValue.mcscore_set.filter(modelMetricLink__id__exact=self.id)[0].score
			else: #if self.metric.metricType == "D":
				return observations[0].value
		
		elif nobs == 0:
			if self.missingValuePolicy == 'D':
				if self.metric.metricType == 'M':
					return self.defaultMCValue.mcscore_set.filter(modelMetricLink__id__exact=self.id)[0].score
				elif self.metric.metricType == 'D':
					return self.defaultDecimalValue
			else: # metric.missingValuePolicy == 'I':
				return None
		
		elif nobs > 1:
			if self.metric.metricType == 'M':
				if self.duplicateValuePolicy == 'A':
					return self.defaultMCValue.mcscore_set.filter(modelMetricLink__id__exact=self.id)[0].score
				if self.duplicateValuePolicy == 'D':
					return self.defaultMCValue.mcscore_set.filter(modelMetricLink__id__exact=self.id)[0].score
			if self.metric.metricType == 'D':
				if self.duplicateValuePolicy == 'A':
					total = 0
					for obs in observations:
						total += obs.value
					return total / nobs
				elif self.duplicateValuePolicy == 'D':
					return self.defaultDecimalValue
				else:
					return None
					
		return -1
		
	
	def save(self, *args, **kwargs):
		super(ModelMetricLink, self).save()
		for option in self.metric.mcoption_set.all():
			try:
				s = MCScore(
					option = option,
					modelMetricLink = self,
					score = 0
				)
				s.save()
			except:
				pass

class RiskModel(models.Model):
	name = models.CharField(max_length=200)
	
	project = models.ForeignKey('projects.project')
	
	# version = models.IntegerField(editable=False)
	
	metrics = models.ManyToManyField('Metric',through=ModelMetricLink)

	def __unicode__(self):
		return self.name
	
	def eval(self,community):
		total = 0
		for mml in RiskModel.objects.get(pk=self.id).modelmetriclink_set.all():
			score = mml.eval(community)
			if score is None:
				return None
			else:
				total += score
		
		return total
				

class RiskModelForm(ModelForm):
	class Meta:
		model = RiskModel
		widgets = {
			# 'metricType': RadioSelect,
		}

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<link href="/static/css/main.css" rel="stylesheet" type="text/css" />

	<script language="JavaScript" src="/static/js/jquery-1.5.min.js"></script>
	<script language="JavaScript" src="/static/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui-1.8.11.custom.min.js"></script>

	
	<script>
		function enable_metric_js(){
			$('.option-order').hide();
			$('.option-delete').hide();
			$('#options-header').hide();
		
			$('.rm-inline').click(function(){
				$(this).parents('tr.form-row').find('input:checkbox').attr('checked', true);
				$(this).parents('tr.form-row').hide("fade");
				return false;
			});
		
		
			$('#add-option').click(function(){
			
			});
	
			$('#id_metric-metricType').change(updateOptionsPane);
		}
		
		function updateOptionsPane(){	
			if($('#id_metric-metricType').val() == 'D'){
				$('#right-pane table').hide();
				$('#d-specific').show("fade");
			}
			if($('#id_metric-metricType').val	() == 'M'){
				$('#right-pane table').hide();
				$('#m-specific').show("fade");
			}
		}
	
		function enable_action_tabs(){

			$('.a-ctl.inline').click(function(){
				var url = $(this).attr("href") + " #action-inner";
				
				$('.a-ctl.active').removeClass("active").addClass("inactive");
				$(this).removeClass("inactive");
				$(this).addClass("active");

				$("#action-outer").hide("fade",function(){
					$("#action-outer").empty();
					$(this).load(url,function(){
						enable_tokens();
						enable_metric_js();
						updateOptionsPane();
						$("#action-outer").show("fade");
					});
				});
				
				return false;
			});
		}
		
		function enable_tables(){
			$('table.sortable').dataTable();
		}
		
		function enable_tokens(){
			$(".tokenized").each(function(){
				var query_url = '/' + $(this).attr('class').match(/ajaxurl-([\w-]+)/)[1].replace("-","/");
				
				$(this).tokenInput(query_url,{
					classes: {
				    tokenList: "token-input-list-facebook",
				    token: "token-input-token-facebook",
				    tokenDelete: "token-input-delete-token-facebook",
				    selectedToken: "token-input-selected-token-facebook",
				    highlightedToken: "token-input-highlighted-token-facebook",
				    dropdown: "token-input-dropdown-facebook",
				    dropdownItem: "token-input-dropdown-item-facebook",
				    dropdownItem2: "token-input-dropdown-item2-facebook",
				    selectedDropdownItem: "token-input-selected-dropdown-item-facebook",
				    inputToken: "token-input-input-token-facebook",
					// preventDuplicates: true,
				}})
			});
			$('.tokenized').parents('form').find("input:submit").click(function(){
				var fields = new Array;
				$('.tokenized').siblings('ul').find('li p').each(function(){
					fields.push($(this).text());
				});
				$(".tokenized").val(fields.join(';'));
			});
		}
	</script>
	
	<script language="JavaScript">
		$(document).ready(function(){
			enable_action_tabs();
			enable_tables();
			updateOptionsPane();
		});
	</script>
	
	<script language="JavaScript">
		$(document).ready(function(){
			
			//navigation
			$("ul.tabs li").live('click',function(){
				var url;
				var direction_in;
				var direction_out;
				
				if($(this).index() == $("ul.tabs li.active").index()){
					return false;
				}
				if($(this).index() > $("ul.tabs li.active").index()){
					direction_in="left";
					direction_out="right";
				}else{
					direction_in="right";
					direction_out="left";
				}
				
				//get the uri of the referenced page part
				var url = $(this).children("a").attr("href") + " #tab-content";
				
				$(".tabs li.active").addClass("inactive").removeClass("active");
				$(this).removeClass("inactive").addClass("active");
				
				
				$("#tab-container").
					hide("slide",{"direction":direction_in},200,function(){
						$(this).load(url,function(){
							enable_action_tabs();
							enable_tables();
							$("#tab-container").show("slide",{"direction":direction_out},200);
						});
					});
			
				return false;
			});

		});
	</script>
	

	
	<script type="text/javascript" src="/static/js/jquery.tokeninput.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/css/token-input.css" />
	
	
	
	<script>
	$(document).ready(function() {
		$('.choice-row').hide();

		var rightArrow=String.fromCharCode(0x25b6);
		var downArrow=String.fromCharCode(0x25bc);

		$('.group-arrow').click(function(){
			if($(this).text() == rightArrow){
				$(this).parents('tbody').children('.choice-row').show();
				$(this).text(downArrow)
			}
			else{
				$(this).parents('tbody').children('.choice-row').hide();
				$(this).text(rightArrow);
			}
			return false;
		});


	});

	</script>
	
	<script>
	$(document).ready(function() {
		
		$('.rm-inline').parents('td').find('input:checkbox').hide();
	
		$('.rm-inline').click(function(){
			$(this).parents('td').find('input:checkbox').attr('checked', true);
			$(this).parents('tbody').hide("fade");
			return false;
		});


	});

	</script>
	
	

	
</head>
<body>
<div id="container">
	<div id="header">
		<div id="logo"></div>
			
		<div id="user-info">
		{% if user.is_authenticated %}
		<div class="cur-user">Hi {{ user.username }} / <a href="/accounts/logout/">Logout</a></div>
		{% else %}
		<div class="cur-user"><a href="/accounts/login/">Login</a></div>
		{% endif %}
		</div>
	</div>

	<div id="content">
			{% block content %}{% endblock %}
	</div>
</div>
</body>

</html>

templates/login.html
{% extends "base.html" %}


{% block content %}

{% if form.errors %}
<p class="middle error">Your username and password didn't match. Please try again.</p>
{% endif %}

<form action="." method="post">

{% csrf_token %}
<table>
<tr>
    <td><label for="username">User name:</label></td>
    <td><input type="text" name="username" value="" id="username"></td>
</tr>
<tr>
    <td><label for="password">Password:</label></td>
    <td><input type="password" name="password" value="" id="password"></td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/register.html
{% extends "base.html" %}


{% block content %}


<table width="100%">
<tr>
<td width="50%">
<h3>Log in</h3>
<form action="." method="post" autocomplete="off">
{% csrf_token %}
{% if form.errors %}
<p class="submit-stripe red"> &#x26A0; Your username and password didn't match. Please try again. </p>
{% endif %}
<div class="form-panel gray">
<table>
<tr>
    <td><label for="username">User name:</label></td>
    <td><input type="text" name="username" value="" id="username"></td>
</tr>
<tr>
    <td><label for="password">Choose a password:</label></td>
    <td><input type="password" name="password" value="" id="password"></td>
</tr>
<tr>
    <td><label for="password">Confirm password:</label></td>
    <td><input type="password" name="password" value="" id="password"></td>
</tr>
</table>
</div>

<p id="submit-container" class="submit-stripe gray">
<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</p>

</td>
<td width="50%">
</td>
</tr>
</table>


</form>


{% endblock %}